FROM ubuntu:18.04
LABEL maintainer="bharadwajaashay@gmail.com"
RUN apt-get update -y && \
apt-get install -y python3 python3-pip
WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY . /app

CMD ["python", "app.py"]
