FROM ubuntu:18.04
LABEL maintainer="bharadwajaashay@gmail.com"
RUN apt-get update -y && \
apt-get install -y python3 python3-pip
WORKDIR /app
RUN pip3 install pytz
COPY requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt

COPY . /app

ENTRYPOINT [ "python3" ]
CMD [ "app.py" ]
