openapi: 3.0.0
info:
  description: This API checks health for all services
  version: "1.0.0"
  title: Reading API
  contact:
    email: mmulder10@bcit.ca
tags:
  - name: store
    description: Operations available to medical devices
paths:
  /status:
    get:
      summary: Get the status of all services
      operationId: app.get_status
      responses:
        '200':
          description: Successful response
          
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ReadingStats'
                receiver: "Running"
                storage: "Down"
                processing: "Running"
                audit: "Running"
                last_update: "2022-03-22T11:12:23"
        '500':
          description: Internal Server Error
  components:
  schemas:
    ReadingStats:
      required:
        receiver
        storage
        processing
        audit
        last_update
      properties:
        receiver:
          type: string
          example: "Running"
        storage:
          type: string
          example: "Down"
        processing:
          type: string
          example: "Running"
        audit:
          type: string
          example: "Down"
        timestamp:
          type: string
          example: "2023-11-02 09:41:25.829461"
      type: object

