FROM ubuntu:18.04
LABEL maintainer="bharadwajaashay@gmail.com"

RUN apt-get update -y && \
    apt-get install -y python3 python3-pip

# Copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip3 install -r requirements.txt

# Copy the rest of the application code
COPY . /app

# Set the entry point for the container
ENTRYPOINT ["python3", "app.py"]

# Set the default command to run when the container starts
CMD ["app.py"]
