openapi: 3.0.0
info:
  description: This API receives reading events from medical devices
  version: "1.0.0"
  title: Reading API
  contact:
    email: mmulder10@bcit.ca
tags:
  - name: store
    description: Operations available to medical devices
paths:
  /inventory-item:
    post:
      tags:
        - store
      summary: reports a inventory item
      operationId: app.report_inventory_item
      description: Adds a new inventory item
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryItem'
        description: Reading item to add

  /standard-order:
    post:
      tags:
        - store
      summary: reports a standard order
      operationId: app.report_standard_order
      description: Adds a standard order
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StandardOrder'
        description: Reading item to add

components:
  schemas:
    InventoryItem:
      required:
        - product_id
        - SKU
        - product_name
        - price
        - compatibility
      properties:
        product_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        SKU:
          type: string
          example: A12345
        product_name:
          type: string
          example: CTS Air intake
        price:
          type: integer  # Corrected the data type
          example: 100
        compatibility:
          type: string
          example: BMW f32 2010-2016
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        trace_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
      type: object

    StandardOrder:
      required:
        - order_id
        - customer_name
        - product_name
        - shipping_address
        - total_amount
        - timestamp
      properties:
        order_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        customer_name:
          type: string
          example: Aashay Bharadwaj
        product_name:
          type: string
          example: BMW Charge pipe
        shipping_address:
          type: string
          example: 1234 Scott Rd
        total_amount:
          type: integer  # Corrected the data type
          example: 200
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        trace_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
      type: object