pipeline {
    agent any

    stages {
        stage('Deploy') {
            steps {
                script {
                    // Define your SSH credentials ID (replace 'your-ssh-credentials-id' with the actual ID)
                    def sshCredentialsId = 'ssh-agent'

                    // Azure VM details
                    def azureUser = 'azureuser'
                    def azureHost = '172.203.81.213'

                    // Start the SSH agent and use the specified credentials
                    sshagent(credentials: [sshCredentialsId]) {
                        // SSH command to execute on the remote server
                        sh "chmod 600 /var/jenkins_home/workspace/microservices_cd@tmp/private_key_7271349975567045728.key"
                        sh "ssh -o StrictHostKeyChecking=no azureuser@172.203.81.213 'echo Hello from Jenkins'"

                    }
                }
            }
        }

        // Add more stages as needed
    }
}
